Rails.application.routes.draw do
  # get 'banks/index'
  # get 'banks/create'
  # get 'banks/new'
  # get 'banks/edit'
  # get 'banks/show'
  # get 'banks/update'
  # get 'banks/delete'
  # get 'teams/index'
  # get 'teams/create'
  # get 'teams/new'
  # get 'teams/edit'
  # get 'teams/show'
  # get 'teams/update'
  # get 'teams/delete'
  # get 'departments/index'
  # get 'departments/create'
  # get 'departments/new'
  # get 'departments/edit'
  # get 'departments/show'
  # get 'departments/update'
  # get 'departments/delete'
  # get 'employees/index'
  # get 'employees/create'
  # get 'employees/new'
  # get 'employees/edit'
  # get 'employees/show'
  # get 'employees/update'
  # get 'employees/delete'
  # get 'books/index'
  # get 'books/create'
  # get 'books/new'
  # get 'books/show'
  # get 'books/edit'
  # get 'books/update'
  # get 'books/destroy'
  # get 'books/index'
  # get 'books/create'
  # get 'books/new'
  # get 'books/show'
  # get 'books/edit'
  # get 'books/update'
  # get 'books/delete'
  # get 'authors/index'
  # get 'authors/create'
  # get 'authors/new'
  # get 'authors/show'
  # get 'authors/edit'
  # get 'authors/update'
  # get 'authors/delete'
  # get 'index/create'
  # get 'index/new'
  # get 'index/show'
  # get 'index/edit'
  # get 'index/update'
  # get 'index/delete'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "employees#index"
  resources :employees
  resources :deaprtments
  resources :teams
  resources :banks

end
